## Intro

Per installare scikit-learn:

In [1]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\andre\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

## PCA (Analisi Componenti Principali)
L’obiettivo della riduzione di dimensionalità è di ridurre il numero di variabili presenti un dataset perdendo il numero minore possibile di features rilevanti per lo studio in essere. 

In [3]:
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])

In [7]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(X)

PCA(n_components=2)

In [12]:
pca.explained_variance_ratio_

array([0.99244289, 0.00755711])

In [13]:
pca.singular_values_

array([6.30061232, 0.54980396])

In [10]:
pca.components_

array([[-0.83849224, -0.54491354],
       [ 0.54491354, -0.83849224]])

In [11]:
pca.explained_variance_

array([7.93954312, 0.06045688])

In [ ]:
# DA PROVARE ANCORA

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

def do_pca(dataframe, columns):
    '''
        Pca on some columns of a dataframe

        Attributes:
            - dataframe     (pandas.DataFrame)
            - columns       ([string]) : list of columns 

        Returns:
            - pca
    '''
    assert type(dataframe) == pd.DataFrame
    assert columns is not None and len(columns) > 0


    cp = dataframe.copy()
    cp = dataframe.replace([np.inf, -np.inf], np.nan).fillna(value=0, inplace=False)
    x = cp[columns].values

    # Standardizing the features
    x = StandardScaler().fit_transform(x)
    # fitting
    pca = PCA().fit(x)
    
    return pca.transform(x)

In [ ]:
# DA PROVARE

import numpy as np
import matplotlib.pylab as plt

# Import dependencies
import plotly
import plotly.graph_objs as go

# Configure Plotly to be rendered inline in the notebook.
plotly.offline.init_notebook_mode()

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

def pca_two_vs_three_visualization(dataframe, columns, classes=None):
        '''
        PCA visualization in 3 dim and 2 dim.

        Attributes:
                - dataframe: (pandas.DataFrame) 
                - columns: (array[string]) columns to use for PCA
                - classes: (array[string] OR array[int]) array of colors or array of values for auto-colorize
        '''

        # Estraggo features basandomi sulle colonne
        cp = dataframe.copy()
        # Replace -inf and inf with zeros
        cp = dataframe.replace([np.inf, -np.inf], np.nan).fillna(value=0, inplace=False)
        x = cp[columns].values
        # Standardizing the features
        x = StandardScaler().fit_transform(x)    
        pca = PCA(n_components=3)
        principalComponents = pca.fit_transform(x)

        fig = plt.figure(figsize=(20,10))
        # First 2 components
        ax1 = fig.add_subplot(121)
        ax1.scatter(principalComponents[:,0], principalComponents[:,1], c=classes, cmap=plt.cm.Spectral, alpha=0.4)
        # First 3 components
        ax2 = fig.add_subplot(1, 2, 2, projection='3d')
        ax2.scatter(principalComponents[:,0], principalComponents[:,1], principalComponents[:,2], c=classes, cmap=plt.cm.Spectral, alpha=0.4)      
        ax2.w_xaxis.set_ticklabels([])
        ax2.w_yaxis.set_ticklabels([])
        ax2.w_zaxis.set_ticklabels([])

        ax1.set_title('PCA - first 2 components')
        ax2.set_title('PCA - first 3 components')

In [ ]:
# DA PROVARE

import numpy as np
import matplotlib.pylab as plt

# Import dependencies
import plotly
import plotly.graph_objs as go

# Configure Plotly to be rendered inline in the notebook.
plotly.offline.init_notebook_mode()

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

def super_pca_visualization(principal_components, classes):
        '''

        Attributes:
                - principal_components          (np.array[]) : principal components
                - classes                       ([numeric])  : list of different classes to color the plot (same size of principal_components.shape[0])
        '''

        assert principal_components.shape[0] == classes.shape[0], 'The length of the classes need to be the same of principal_components.shape[0]

        # doing pca
        pc = principal_components

        pcs = dict()

        for single_class in classes.unique():
        i = 0
        actual_class_pc = []
        for c in classes:
                if c == single_class:
                actual_class_pc.append(pc[i])
                
                i += 1
                
        if len(actual_class_pc) > 0:
                pcs[single_class] = actual_class_pc
                
        traces = []        
                
        for key, value in pcs.items():
        pc_np = np.asarray(value)

        # Configure the trace.
        trace = go.Scatter3d(
                x=pc_np[:,0],  # <-- Put your data instead
                y=pc_np[:,1],  # <-- Put your data instead
                z=pc_np[:,2],  # <-- Put your data instead
                mode='markers',
                name=str(key),
                marker={
                'size': 2,
                'opacity': 0.8,
                }
        )

        traces.append(trace)

        # Configure the layout.
        layout = go.Layout(
        margin={'l': 0, 'r': 0, 'b': 0, 't': 0}
        )

        plot_figure = go.Figure(data=traces, layout=layout)

        # Render the plot.

        plotly.offline.iplot(plot_figure)

        return pcs

## KernelPCA
Estensione della PCA che raggiunge la riduzione di dimensionalità non-lineare tramite l’uso di Kernel

In [ ]:
from sklearn.decomposition import KernelPCA
transformer = KernelPCA(n_components=7, kernel='linear')
X_transformed = transformer.fit_transform(X)

In [ ]:
X_transformed.shape

## FactorAnalysis 
Modello probabilistico, simile alla PCA ma non si possono fare assunzioni sulle componenti ottenute

In [ ]:
from sklearn.decomposition import FactorAnalysis
transformer = FactorAnalysis(n_components=7, kernel='linear')
X_transformed = transformer.fit_transform(X)

In [ ]:
X_transformed.shape

## Non-Negative Matrix Factorization (NMF)
approccio alternativo alla decomposizione che assume che i dati e le componenti siano non negativi

In [14]:
X = np.array([[1, 1], [2, 1], [3, 1.2], [4, 1], [5, 0.8], [6, 1]])

In [ ]:
from sklearn.decomposition import NMF
model = NMF(n_components=2, init='random', random_state=0)
W = model.fit_transform(X)
H = model.components_